/**
 * GENERATED from src/core/ccep/workflows/council.yml by scripts/render-agent-commands.ts — DO NOT EDIT.
 *
 * Q3 mirror of the canonical council workflow: the packaged bundle does not
 * ship the YAML asset, so profiles.ts falls back to this copy when the file
 * is absent. Regenerated by renderAll() and covered by check:drift.
 */
import type { WorkflowProfileInput } from '../../validation/schemas';

export const COUNCIL_FALLBACK_PROFILE: WorkflowProfileInput = {
  "id": "council",
  "version": 1,
  "command": "council",
  "phases": [
    {
      "id": "wayfinding",
      "agent": "repo-explorer",
      "outputSchema": "agent-output"
    },
    {
      "id": "deliberation",
      "agents": [
        "task-coach",
        "architect",
        "devil"
      ],
      "skill": "council",
      "outputSchema": "planner-output",
      "stopGate": "confirmation"
    },
    {
      "id": "tdd",
      "agent": "tester",
      "requires": "red-state"
    },
    {
      "id": "implement",
      "agent": "implementer"
    },
    {
      "id": "council-review",
      "agents": [
        "architect",
        "product",
        "delivery",
        "data-ops",
        "security-reviewer",
        "devil"
      ],
      "skill": "council",
      "outputSchema": "council-verdict"
    }
  ],
  "routing": {
    "default": [
      "wayfinding",
      "deliberation",
      "tdd",
      "implement",
      "council-review"
    ]
  },
  "confirmationGate": {
    "stopOnHighRisk": true,
    "stopOnQuestions": true
  }
};
