import type { WorkflowCommandInput, WorkflowProfileInput } from '../../validation/schemas';

const baseGate = { stopOnHighRisk: true, stopOnQuestions: true };

export const WORKFLOW_PROFILES: Record<WorkflowCommandInput, WorkflowProfileInput> = {
  feature: {
    id: 'feature',
    version: 1,
    command: 'feature',
    taskCard: {
      type: 'feature',
      requiredFields: ['title', 'type', 'risk', 'scope', 'context', 'acceptanceCriteria'],
    },
    phases: [
      { id: 'wayfinding', agent: 'repo-explorer', outputSchema: 'agent-output' },
      { id: 'intake', agent: 'task-coach', outputSchema: 'planner-output', stopGate: 'confirmation' },
      { id: 'design', agent: 'architect', outputSchema: 'technical-plan', stopGate: 'approval' },
      { id: 'test', agent: 'tester', dependsOn: ['design'] },
      { id: 'implement', agent: 'implementer', dependsOn: ['test'] },
      { id: 'review', agent: 'reviewer' },
      { id: 'docs', agent: 'docs', parallelWith: ['review'] },
    ],
    routing: { default: ['wayfinding', 'intake', 'design', 'test', 'implement', 'review', 'docs'] },
    confirmationGate: baseGate,
  },
  fix: {
    id: 'fix',
    version: 1,
    command: 'fix',
    taskCard: {
      type: 'fix',
      requiredFields: [
        'actualBehavior',
        'expectedBehavior',
        'reproductionSteps',
        'risk',
        'scope',
      ],
    },
    phases: [
      { id: 'wayfinding', agent: 'repo-explorer', outputSchema: 'agent-output' },
      { id: 'intake', agent: 'task-coach', outputSchema: 'fix-intake-output', stopGate: 'confirmation' },
      { id: 'test', agent: 'tester' },
      { id: 'implement', agent: 'implementer', dependsOn: ['test'] },
      { id: 'review', agent: 'reviewer' },
    ],
    routing: {
      default: ['wayfinding', 'intake', 'test', 'implement'],
      riskRules: [
        { when: { risk: 'low' }, then: ['wayfinding', 'test', 'implement'] },
        { when: { risk: ['medium', 'high'] }, then: ['wayfinding', 'test', 'implement', 'review'] },
      ],
    },
    confirmationGate: baseGate,
  },
  refactor: {
    id: 'refactor',
    version: 1,
    command: 'refactor',
    taskCard: {
      type: 'refactor',
      requiredFields: ['title', 'risk', 'scope', 'acceptanceCriteria'],
    },
    phases: [
      { id: 'intake', agent: 'task-coach', outputSchema: 'planner-output' },
      { id: 'design', agent: 'architect', outputSchema: 'technical-plan' },
      { id: 'implement', agent: 'implementer' },
      { id: 'audit', agent: 'complexity-auditor', outputSchema: 'complexity-audit' },
      { id: 'review', agent: 'reviewer' },
    ],
    routing: { default: ['intake', 'design', 'implement', 'audit', 'review'] },
    confirmationGate: baseGate,
  },
  review: {
    id: 'review',
    version: 1,
    command: 'review',
    intakeSchema: 'review-target',
    phases: [
      { id: 'diff-collection', agent: 'reviewer', type: 'diff' },
      { id: 'review', agent: 'reviewer', outputSchema: 'review-report' },
    ],
    routing: { default: ['diff-collection', 'review'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: false },
  },
  'test-plan': {
    id: 'test-plan',
    version: 1,
    command: 'test-plan',
    taskCard: { type: 'test', requiredFields: ['scope', 'acceptanceCriteria'] },
    phases: [
      { id: 'intake', agent: 'task-coach', outputSchema: 'planner-output' },
      { id: 'plan', agent: 'tester', outputSchema: 'test-plan' },
    ],
    routing: { default: ['intake', 'plan'] },
    confirmationGate: baseGate,
  },
  'tdd-cycle': {
    id: 'tdd-cycle',
    version: 1,
    command: 'tdd-cycle',
    taskCard: { type: 'test', requiredFields: ['scope', 'acceptanceCriteria'] },
    phases: [
      { id: 'test', agent: 'tester', requires: 'red-state' },
      { id: 'implement', agent: 'implementer' },
    ],
    routing: { default: ['test', 'implement'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: true },
  },
  'api-contract': {
    id: 'api-contract',
    version: 1,
    command: 'api-contract',
    taskCard: { type: 'feature', requiredFields: ['scope', 'acceptanceCriteria'] },
    phases: [
      { id: 'contract', agent: 'contract-builder', outputSchema: 'api-contract' },
      { id: 'design', agent: 'architect', outputSchema: 'technical-plan' },
    ],
    routing: { default: ['contract', 'design'] },
    confirmationGate: baseGate,
  },
  'db-migration': {
    id: 'db-migration',
    version: 1,
    command: 'db-migration',
    taskCard: { type: 'feature', requiredFields: ['scope', 'risk', 'acceptanceCriteria'] },
    phases: [
      { id: 'design', agent: 'architect', outputSchema: 'technical-plan' },
      { id: 'test', agent: 'tester' },
      { id: 'implement', agent: 'implementer', dependsOn: ['test'] },
      { id: 'review', agent: 'reviewer' },
    ],
    routing: { default: ['design', 'test', 'implement', 'review'] },
    confirmationGate: baseGate,
  },
  pagespeed: {
    id: 'pagespeed',
    version: 1,
    command: 'pagespeed',
    intakeSchema: 'pagespeed-url',
    phases: [
      { id: 'psi-fetch', agent: 'repo-explorer', type: 'external' },
      { id: 'report', agent: 'docs', outputSchema: 'pagespeed-report' },
    ],
    routing: { default: ['psi-fetch', 'report'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: false },
  },
  openspec: {
    id: 'openspec',
    version: 1,
    command: 'openspec',
    intakeSchema: 'openspec-backlog-item',
    phases: [
      { id: 'validate-backlog', agent: 'orchestrator', type: 'cli-gate' },
      { id: 'discover', agent: 'repo-explorer' },
      { id: 'design', agent: 'architect' },
      { id: 'test', agent: 'tester' },
      { id: 'implement', agent: 'implementer', dependsOn: ['test'] },
      { id: 'review', agent: 'reviewer' },
    ],
    routing: { default: ['validate-backlog', 'discover', 'design', 'test', 'implement', 'review'] },
    confirmationGate: baseGate,
  },
  scorecard: {
    id: 'scorecard',
    version: 1,
    command: 'scorecard',
    intakeSchema: 'scorecard-task-id',
    phases: [
      { id: 'create', agent: 'orchestrator', type: 'cli-gate' },
      { id: 'evaluate', agent: 'reviewer', outputSchema: 'scorecard-record' },
    ],
    routing: { default: ['create', 'evaluate'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: false },
  },
  council: {
    id: 'council',
    version: 1,
    command: 'council',
    phases: [
      { id: 'wayfinding', agent: 'repo-explorer', outputSchema: 'agent-output' },
      {
        id: 'deliberation',
        agents: ['task-coach', 'architect', 'devil'],
        skill: 'council',
        outputSchema: 'planner-output',
        stopGate: 'confirmation',
      },
      { id: 'tdd', agent: 'tester', requires: 'red-state' },
      { id: 'implement', agent: 'implementer' },
      {
        id: 'council-review',
        skill: 'council',
        outputSchema: 'council-verdict',
      },
    ],
    routing: { default: ['wayfinding', 'deliberation', 'tdd', 'implement', 'council-review'] },
    confirmationGate: baseGate,
  },
  iterative: {
    id: 'iterative',
    version: 1,
    command: 'iterative',
    taskCard: {
      type: 'feature',
      requiredFields: ['title', 'type', 'risk', 'scope', 'context', 'acceptanceCriteria'],
    },
    phases: [
      { id: 'wayfinding', agent: 'repo-explorer', outputSchema: 'agent-output' },
      { id: 'intake', agent: 'task-coach', outputSchema: 'planner-output', stopGate: 'confirmation' },
      { id: 'contract', agent: 'contract-builder', outputSchema: 'api-contract' },
      { id: 'design', agent: 'architect', outputSchema: 'technical-plan', stopGate: 'approval' },
      { id: 'test', agent: 'tester', dependsOn: ['design'] },
      { id: 'implement', agent: 'implementer', dependsOn: ['test'] },
      { id: 'council-review', skill: 'council', outputSchema: 'council-verdict' },
      { id: 'docs', agent: 'docs' },
    ],
    routing: {
      default: [
        'wayfinding',
        'intake',
        'contract',
        'design',
        'test',
        'implement',
        'council-review',
        'docs',
      ],
    },
    confirmationGate: baseGate,
  },
  explore: {
    id: 'explore',
    version: 1,
    command: 'explore',
    intakeSchema: 'explore-query',
    phases: [
      { id: 'map', agent: 'repo-explorer', outputSchema: 'agent-output' },
      { id: 'suggest-next', agent: 'orchestrator', outputSchema: 'agent-output' },
    ],
    routing: { default: ['map', 'suggest-next'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: false },
  },
  triage: {
    id: 'triage',
    version: 1,
    command: 'triage',
    taskCard: {
      type: 'feature',
      requiredFields: ['title', 'type', 'risk', 'scope'],
    },
    phases: [
      { id: 'classify', agent: 'task-coach', outputSchema: 'planner-output', stopGate: 'confirmation' },
    ],
    routing: { default: ['classify'] },
    confirmationGate: baseGate,
  },
  prototype: {
    id: 'prototype',
    version: 1,
    command: 'prototype',
    taskCard: {
      type: 'feature',
      requiredFields: ['title', 'scope', 'acceptanceCriteria'],
    },
    phases: [
      { id: 'bounds', agent: 'architect', outputSchema: 'technical-plan', stopGate: 'approval' },
      { id: 'spike', agent: 'implementer' },
    ],
    routing: { default: ['bounds', 'spike'] },
    confirmationGate: baseGate,
  },
  handoff: {
    id: 'handoff',
    version: 1,
    command: 'handoff',
    intakeSchema: 'handoff-session',
    phases: [
      { id: 'compact', agent: 'docs', outputSchema: 'agent-output' },
    ],
    routing: { default: ['compact'] },
    confirmationGate: { stopOnHighRisk: true, stopOnQuestions: true },
  },
  clarify: {
    id: 'clarify',
    version: 1,
    command: 'clarify',
    intakeSchema: 'clarify-deliverable',
    phases: [
      { id: 're-explain', agent: 'task-coach', outputSchema: 'planner-output' },
    ],
    routing: { default: ['re-explain'] },
    confirmationGate: { stopOnHighRisk: false, stopOnQuestions: true },
  },
};
