import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import type { OutputMode } from '../utils/logger';

export interface DebtHarvestOptions {
  readonly projectRoot: string;
  readonly dir?: string;
  readonly output: OutputMode;
}

interface DebtEntry {
  file: string;
  line: number;
  reason: string;
  tag?: string;
}

const DEFER_REGEX = /\/\/\s*defer\s*[-:]\s*(.+?)(?:\s*--(\w+))?\s*$/gm;

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.rb', '.go', '.rs', '.java', '.kt',
  '.php', '.cs', '.swift', '.scala', '.sh',
]);

async function walkDir(dir: string, extensions: Set<string>): Promise<string[]> {
  const results: string[] = [];
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        // Skip hidden dirs and node_modules
        if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
        results.push(...await walkDir(fullPath, extensions));
      } else if (extensions.has(extname(entry.name))) {
        results.push(fullPath);
      }
    }
  } catch {
    // Directory doesn't exist or not readable — skip silently
  }
  return results;
}

function extractDefers(content: string, filePath: string): DebtEntry[] {
  const entries: DebtEntry[] = [];
  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    // Reset lastIndex for global regex
    DEFER_REGEX.lastIndex = 0;
    const match = DEFER_REGEX.exec(line);
    if (match) {
      entries.push({
        file: filePath,
        line: i + 1,
        reason: match[1]!.trim(),
        tag: match[2],
      });
    }
  }
  return entries;
}

function renderLedger(entries: DebtEntry[]): string {
  const grouped = new Map<string, DebtEntry[]>();
  for (const entry of entries) {
    const tag = entry.tag ?? 'unclassified';
    const group = grouped.get(tag) ?? [];
    group.push(entry);
    grouped.set(tag, group);
  }

  const lines: string[] = [
    '<!-- CODECONDUCTOR:BEGIN managed -->',
    '',
    '# Debt Ledger',
    '',
    '> Auto-generated by `codeconductor debt-harvest`. Do not edit manually.',
    '',
  ];

  const sortedTags = [...grouped.keys()].sort();
  for (const tag of sortedTags) {
    const tagEntries = grouped.get(tag)!;
    lines.push(`## ${tag}`);
    lines.push('');
    lines.push('| File | Line | Reason |');
    lines.push('| ---- | ---- | ------ |');
    for (const entry of tagEntries) {
      lines.push(`| ${entry.file} | ${entry.line} | ${entry.reason} |`);
    }
    lines.push('');
  }

  lines.push('<!-- CODECONDUCTOR:END managed -->');
  lines.push('');
  return lines.join('\n');
}

/**
 * debt-harvest command — scans source files for "// defer - [reason]"
 * comments and consolidates them into .codeconductor/debt-ledger.md.
 *
 * Read-only on source files. Only writes to debt-ledger.md.
 */
export async function debtHarvestCommand(
  options: DebtHarvestOptions,
): Promise<{ code: number; data?: unknown }> {
  const { projectRoot, dir = 'src', output } = options;

  try {
    const targetDir = join(projectRoot, dir);
    const files = await walkDir(targetDir, SOURCE_EXTENSIONS);

    const allEntries: DebtEntry[] = [];
    for (const file of files) {
      const content = await readFile(file, 'utf-8');
      const entries = extractDefers(content, relative(projectRoot, file));
      allEntries.push(...entries);
    }

    // Ensure .codeconductor directory exists
    const ledgerDir = join(projectRoot, '.codeconductor');
    await mkdir(ledgerDir, { recursive: true });

    // Write ledger
    const ledgerPath = join(ledgerDir, 'debt-ledger.md');
    const ledgerContent = renderLedger(allEntries);
    await writeFile(ledgerPath, ledgerContent, 'utf-8');

    if (output === 'json') {
      return {
        code: 0,
        data: {
          success: true,
          command: 'debt-harvest',
          entries: allEntries,
          entryCount: allEntries.length,
          ledger: ledgerPath,
        },
      };
    }

    return {
      code: 0,
      data: {
        success: true,
        command: 'debt-harvest',
        message: `Found ${allEntries.length} deferred item(s) across ${files.length} file(s). Ledger written to ${ledgerPath}`,
        entries: allEntries,
      },
    };
  } catch (error) {
    return {
      code: 1,
      data: {
        success: false,
        command: 'debt-harvest',
        errors: [String(error)],
      },
    };
  }
}
