import { describe, expect, test } from 'bun:test';
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { loadSharedSkills, syncAll } from '../../../scripts/sync-shared-skills';

const ROOT = resolve(import.meta.dir, '../../..');

describe('shared-skills.yml', () => {
  const entries = loadSharedSkills();

  test('lists at least one shared skill', () => {
    expect(entries.length).toBeGreaterThan(0);
  });

  test('every entry has 2+ targets — a single-target entry cannot be "shared"', () => {
    for (const entry of entries) {
      expect(entry.targets.length).toBeGreaterThanOrEqual(2);
    }
  });

  test('every canonical skills/<name>/SKILL.md exists', () => {
    for (const entry of entries) {
      const path = join(ROOT, 'skills', entry.name, 'SKILL.md');
      expect(existsSync(path)).toBe(true);
    }
  });

  test('every presets/<target>/skills/<name>/SKILL.md matches its canonical source byte-for-byte', () => {
    for (const entry of entries) {
      const canonical = readFileSync(join(ROOT, 'skills', entry.name, 'SKILL.md'), 'utf-8');
      for (const target of entry.targets) {
        const targetPath = join(ROOT, 'presets', target, 'skills', entry.name, 'SKILL.md');
        expect(existsSync(targetPath)).toBe(true);
        expect(readFileSync(targetPath, 'utf-8')).toBe(canonical);
      }
    }
  });
});

// --- BC-026: duplicated-skill coverage guard -------------------------------

/** Skills duplicated across presets are exempt only if they match one of these prefixes. */
const DUPLICATE_ALLOWLIST_PREFIXES: readonly string[] = [
  // cc-*: the codex copy is generated by render:commands and the agy copy is a
  // hand-maintained file in a different format, so sync-shared-skills.ts cannot own them.
  'cc-',
];

/** Names of skills present in 2+ presets that are neither in the manifest nor allowlisted. */
function findUnprotectedDuplicates(
  skillTargets: ReadonlyMap<string, readonly string[]>,
  manifest: readonly { readonly name: string }[],
  allowlistPrefixes: readonly string[]
): string[] {
  const shared = new Set(manifest.map((entry) => entry.name));
  return [...skillTargets.entries()]
    .filter(([, targets]) => targets.length >= 2)
    .filter(([name]) => !shared.has(name))
    .filter(([name]) => !allowlistPrefixes.some((prefix) => name.startsWith(prefix)))
    .map(([name]) => name)
    .sort();
}

/** Scan every child of presets/ (cursor included, dot-dirs excluded): skill = dir with SKILL.md. */
function scanPresetSkills(): Map<string, string[]> {
  const result = new Map<string, string[]>();
  const presetsDir = join(ROOT, 'presets');
  for (const preset of readdirSync(presetsDir, { withFileTypes: true })) {
    if (!preset.isDirectory() || preset.name.startsWith('.')) continue;
    const skillsDir = join(presetsDir, preset.name, 'skills');
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir, { withFileTypes: true })) {
      if (!skill.isDirectory()) continue;
      if (!existsSync(join(skillsDir, skill.name, 'SKILL.md'))) continue;
      result.set(skill.name, [...(result.get(skill.name) ?? []), preset.name]);
    }
  }
  return result;
}

describe('duplicated skill guard (BC-026 FR-001)', () => {
  test('SC-001: flags a skill present in claude and codex that is outside the manifest, naming it', () => {
    const scanned = new Map([['orphan-skill', ['claude', 'codex']]]);
    expect(findUnprotectedDuplicates(scanned, [{ name: 'other' }], DUPLICATE_ALLOWLIST_PREFIXES)).toEqual([
      'orphan-skill',
    ]);
  });

  test('does not flag single-copy skills, manifest skills or allowlisted cc-* skills', () => {
    const scanned = new Map([
      ['solo', ['claude']],
      ['in-manifest', ['claude', 'codex']],
      ['cc-feature', ['codex', 'agy']],
    ]);
    expect(findUnprotectedDuplicates(scanned, [{ name: 'in-manifest' }], DUPLICATE_ALLOWLIST_PREFIXES)).toEqual([]);
  });

  test('allowlist is not stale: every prefix matches at least one real duplicated skill', () => {
    const duplicated = [...scanPresetSkills().entries()].filter(([, targets]) => targets.length >= 2).map(([n]) => n);
    for (const prefix of DUPLICATE_ALLOWLIST_PREFIXES) {
      expect(duplicated.some((name) => name.startsWith(prefix))).toBe(true);
    }
  });

  test('every skill duplicated across presets/ is in shared-skills.yml or allowlisted', () => {
    const missing = findUnprotectedDuplicates(scanPresetSkills(), loadSharedSkills(), DUPLICATE_ALLOWLIST_PREFIXES);
    if (missing.length > 0) {
      throw new Error(
        `${missing.length} skill(s) duplicated across presets/ but missing from shared-skills.yml: ${missing.join(', ')}`
      );
    }
  });
});

// Skills whose cursor copy keeps a hand-maintained `paths:` block or differs in
// content: sync must never overwrite it, so the manifest must not list cursor.
const SKILLS_WITHOUT_CURSOR_TARGET: readonly string[] = [
  'android',
  'backlog',
  'conductor-setup',
  'django-testing',
  'find-skills',
  'laravel-specialist',
  'pagespeed-insights',
  'pagespeed-perf',
  'php-pro',
  'python-django-stack',
  'python-fastapi-stack',
  'security',
  'spring-boot-kotlin',
  'sqlalchemy',
];

describe('stack skills never sync to cursor', () => {
  const manifest = new Map(loadSharedSkills().map((entry) => [entry.name, entry.targets]));

  for (const name of SKILLS_WITHOUT_CURSOR_TARGET) {
    test(`${name} is in shared-skills.yml and does not target cursor`, () => {
      const actual = manifest.get(name);
      expect(actual).toBeDefined();
      expect(actual).not.toContain('cursor');
    });
  }
});

describe('syncAll idempotence (BC-026 FR-002)', () => {
  function snapshotPresetSkills(): Map<string, string> {
    const snapshot = new Map<string, string>();
    for (const [name, targets] of scanPresetSkills()) {
      for (const target of targets) {
        const path = join(ROOT, 'presets', target, 'skills', name, 'SKILL.md');
        snapshot.set(path, readFileSync(path, 'utf-8'));
      }
    }
    return snapshot;
  }

  test('running syncAll() twice leaves every presets/ skill copy unchanged', () => {
    // syncAll writes into presets/, so restore the pre-run content (and remove any
    // newly created copy) in finally: the working tree is never left modified.
    const before = snapshotPresetSkills();
    try {
      syncAll();
      const afterFirst = snapshotPresetSkills();
      syncAll();
      const afterSecond = snapshotPresetSkills();
      expect([...afterFirst.keys()].sort()).toEqual([...afterSecond.keys()].sort());
      for (const [path, content] of afterSecond) {
        expect(content === afterFirst.get(path)).toBe(true);
      }
      // Pre-existing copies are untouched too (green before migration; after it, the
      // sources must already match the committed copies).
      for (const [path, content] of before) {
        expect(afterSecond.get(path) === content).toBe(true);
      }
    } finally {
      for (const path of snapshotPresetSkills().keys()) {
        if (!before.has(path)) rmSync(path);
      }
      for (const [path, content] of before) writeFileSync(path, content);
    }
  });
});
