import { safeFetch, delay } from '../../infrastructure/http/safe-fetch';
import { parseSitemap } from '../../infrastructure/parsers/sitemap-parser';
import type { LlmsTxtEntry, LlmsTxtResult } from './seo-types';

function extractTitle(html: string): string {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? match[1].trim() : '';
}

function extractDescription(html: string): string {
  const patterns = [
    /<meta[^>]*name=["']description["'][^>]*content=["']([^"']*)["']/i,
    /<meta[^>]*content=["']([^"']*)["'][^>]*name=["']description["']/i,
    /<meta[^>]*property=["']og:description["'][^>]*content=["']([^"']*)["']/i,
  ];
  for (const pattern of patterns) {
    const match = html.match(pattern);
    if (match) return match[1].trim();
  }
  return '';
}

function extractFirstParagraph(html: string): string {
  const bodyHtml = html.replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<nav[\s\S]*?<\/nav>/gi, '')
    .replace(/<header[\s\S]*?<\/header>/gi, '')
    .replace(/<footer[\s\S]*?<\/footer>/gi, '');

  const match = bodyHtml.match(/<p[^>]*>([\s\S]*?)<\/p>/i);
  if (!match) return '';

  return match[1].replace(/<[^>]*>/g, '').trim().slice(0, 200);
}

function groupByPathSegment(entries: LlmsTxtEntry[]): Map<string, LlmsTxtEntry[]> {
  const groups = new Map<string, LlmsTxtEntry[]>();

  for (const entry of entries) {
    try {
      const parsed = new URL(entry.url);
      const segments = parsed.pathname.split('/').filter(Boolean);
      const group = segments.length > 0 ? `/${segments[0]}/` : '/';

      if (!groups.has(group)) {
        groups.set(group, []);
      }
      groups.get(group)!.push(entry);
    } catch {
      if (!groups.has('/')) {
        groups.set('/', []);
      }
      groups.get('/')!.push(entry);
    }
  }

  return groups;
}

function formatLlmsTxt(
  siteName: string,
  siteDescription: string,
  entries: LlmsTxtEntry[]
): string {
  const lines: string[] = [];

  lines.push(`# ${siteName}`);
  if (siteDescription) {
    lines.push(`> ${siteDescription}`);
  }
  lines.push('');

  const groups = groupByPathSegment(entries);

  for (const [group, groupEntries] of groups) {
    const groupName = group === '/' ? 'Main Pages' : group.replace(/\//g, '').replace(/-/g, ' ');
    lines.push(`## ${groupName.charAt(0).toUpperCase() + groupName.slice(1)}`);
    lines.push('');

    for (const entry of groupEntries) {
      const desc = entry.description ? `: ${entry.description}` : '';
      lines.push(`- [${entry.title}](${entry.url})${desc}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by CodeConductor SEO on ${new Date().toISOString().split('T')[0]}`);

  return lines.join('\n');
}

export async function generateLlmsTxtFromSitemap(
  sitemapUrl: string,
  options: { delay?: number; maxUrls?: number; onProgress?: (current: number, total: number, url: string) => void } = {}
): Promise<LlmsTxtResult> {
  const { delay: requestDelay = 500, maxUrls, onProgress } = options;

  const sitemapResult = await parseSitemap(sitemapUrl, { delay: requestDelay });

  let urls = sitemapResult.entries.map((e) => e.url);
  if (maxUrls && urls.length > maxUrls) {
    urls = urls.slice(0, maxUrls);
  }

  const entries: LlmsTxtEntry[] = [];
  let siteName = '';
  let siteDescription = '';

  for (let i = 0; i < urls.length; i++) {
    const url = urls[i];

    if (onProgress) {
      onProgress(i + 1, urls.length, url);
    }

    if (i > 0 && requestDelay > 0) {
      await delay(requestDelay);
    }

    try {
      const response = await safeFetch(url);
      const html = response.body;

      const title = extractTitle(html) || url;
      const description = extractDescription(html) || extractFirstParagraph(html);

      if (i === 0) {
        siteName = title;
        siteDescription = extractDescription(html);
      }

      entries.push({ title, url, description });
    } catch {
      entries.push({ title: url, url, description: '' });
    }
  }

  if (!siteName) {
    try {
      siteName = new URL(sitemapUrl).hostname;
    } catch {
      siteName = 'Site';
    }
  }

  const content = formatLlmsTxt(siteName, siteDescription, entries);

  return { content, entries };
}

export async function generateLlmsTxtFromUrl(
  url: string
): Promise<LlmsTxtResult> {
  const response = await safeFetch(url);
  const html = response.body;

  const title = extractTitle(html) || url;
  const description = extractDescription(html) || extractFirstParagraph(html);

  const entries: LlmsTxtEntry[] = [{ title, url, description }];
  const content = formatLlmsTxt(title, description, entries);

  return { content, entries };
}
