import type { AuditReport, PageAuditResult, Severity } from './seo-types';

const SEVERITY_ICONS: Record<Severity, string> = {
  pass: '✓',
  warning: '⚠',
  error: '✗',
  info: 'ℹ',
};

const SEVERITY_COLORS: Record<Severity, string> = {
  pass: '\x1b[32m',
  warning: '\x1b[33m',
  error: '\x1b[31m',
  info: '\x1b[36m',
};

const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';

export function formatCli(report: AuditReport): string {
  const lines: string[] = [];

  lines.push('');
  lines.push(`${BOLD}SEO Audit Report${RESET}`);
  lines.push(`${DIM}Target: ${report.target}${RESET}`);
  lines.push(`${DIM}Time: ${report.timestamp}${RESET}`);
  lines.push(`${DIM}Pages: ${report.pages.length}${RESET}`);
  lines.push('');

  for (const page of report.pages) {
    lines.push(`${BOLD}── ${page.url} (${page.responseTime}ms) ──${RESET}`);

    const grouped = groupByCategory(page.checks);
    for (const [category, checks] of grouped) {
      lines.push(`  ${DIM}${category}${RESET}`);
      for (const check of checks) {
        const icon = SEVERITY_ICONS[check.severity];
        const color = SEVERITY_COLORS[check.severity];
        lines.push(`    ${color}${icon}${RESET} ${check.name}: ${check.message}`);
        if (check.remediation && check.severity !== 'pass') {
          lines.push(`      ${DIM}→ ${check.remediation}${RESET}`);
        }
      }
    }
    lines.push('');
  }

  const { summary } = report;
  lines.push(`${BOLD}Summary${RESET}`);
  lines.push(`  Score: ${summary.score}%`);
  lines.push(`  ${SEVERITY_COLORS.pass}✓ ${summary.passed} passed${RESET}`);
  lines.push(`  ${SEVERITY_COLORS.warning}⚠ ${summary.warnings} warnings${RESET}`);
  lines.push(`  ${SEVERITY_COLORS.error}✗ ${summary.errors} errors${RESET}`);
  lines.push(`  Total checks: ${summary.total}`);
  lines.push('');

  return lines.join('\n');
}

export function formatJson(report: AuditReport): string {
  return JSON.stringify(report, null, 2);
}

export function formatMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  lines.push('# SEO Audit Report');
  lines.push('');
  lines.push(`- **Target:** ${report.target}`);
  lines.push(`- **Date:** ${report.timestamp}`);
  lines.push(`- **Pages audited:** ${report.pages.length}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Score | ${report.summary.score}% |`);
  lines.push(`| Passed | ${report.summary.passed} |`);
  lines.push(`| Warnings | ${report.summary.warnings} |`);
  lines.push(`| Errors | ${report.summary.errors} |`);
  lines.push(`| Total checks | ${report.summary.total} |`);
  lines.push('');

  for (const page of report.pages) {
    lines.push(`## ${page.url}`);
    lines.push('');
    lines.push(`Response time: ${page.responseTime}ms`);
    lines.push('');

    const errors = page.checks.filter((c) => c.severity === 'error');
    const warnings = page.checks.filter((c) => c.severity === 'warning');
    const passed = page.checks.filter((c) => c.severity === 'pass');
    const info = page.checks.filter((c) => c.severity === 'info');

    if (errors.length > 0) {
      lines.push('### Errors');
      lines.push('');
      for (const check of errors) {
        lines.push(`- **${check.name}** (${check.category}): ${check.message}`);
        if (check.remediation) {
          lines.push(`  - Fix: ${check.remediation}`);
        }
      }
      lines.push('');
    }

    if (warnings.length > 0) {
      lines.push('### Warnings');
      lines.push('');
      for (const check of warnings) {
        lines.push(`- **${check.name}** (${check.category}): ${check.message}`);
        if (check.remediation) {
          lines.push(`  - Fix: ${check.remediation}`);
        }
      }
      lines.push('');
    }

    if (passed.length > 0) {
      lines.push('### Passed');
      lines.push('');
      for (const check of passed) {
        lines.push(`- ${check.name}: ${check.message}`);
      }
      lines.push('');
    }

    if (info.length > 0) {
      lines.push('### Info');
      lines.push('');
      for (const check of info) {
        lines.push(`- ${check.name}: ${check.message}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by CodeConductor SEO Audit on ${report.timestamp.split('T')[0]}*`);

  return lines.join('\n');
}

function groupByCategory(checks: PageAuditResult['checks']): Map<string, PageAuditResult['checks']> {
  const groups = new Map<string, PageAuditResult['checks']>();
  for (const check of checks) {
    if (!groups.has(check.category)) {
      groups.set(check.category, []);
    }
    groups.get(check.category)!.push(check);
  }
  return groups;
}

export function computeExitCode(report: AuditReport, failOn: 'error' | 'warning'): number {
  if (report.summary.errors > 0) return 1;
  if (failOn === 'warning' && report.summary.warnings > 0) return 2;
  if (report.summary.warnings > 0) return 0;
  return 0;
}
